name: LobbyUtils
main: de.fredo121.lobbyutils.main.LobbyUtils
version: 0.1
author: fredo121
description: LobbyUtils Plugin using Spigot API 

commands:
  lobby:
    description: Lobby Base Command
    permission: lobby.use
  hub:
    description: Hub Base Command
    permission: lobby.use
    
permissions:
  lobby.use:
    description: Use Lobby Commands
    default: true