name: LobbyUtils
main: de.fredo121.lobbyutils.main.LobbyUtils
version: 0.1
author: fredo121
description: LobbyUtils Plugin using Spigot API 

commands:
  lobby:
    description: Lobby Base Command
    permission: lobby.use
  hub:
    description: Hub Base Command
    permission: lobby.use
  ts:
    description: ts
    permission: lobby.ts
  ts3:
    description: ts3
    permission: lobby.ts
  vote:
    description: vote
    permission: lobby.vote
  web:
    description: web
    permission: lobby.web
    
permissions:
  lobby.use:
    description: Use Lobby Commands
    default: true